site_name: Sopa
repo_name: sopa
copyright: Copyright &copy; 2023 - 2024 Quentin Blampey
theme:
  name: material
  logo: assets/sopa_small_white.png
  favicon: assets/sopa_favicon.png
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Snakemake pipeline: pipeline.md
  - CLI: cli.md
  - API:
    - sopa.stats: api/stats.md
    - sopa.segmentation:
      - sopa.segmentation.shapes: api/segmentation/shapes.md
    - sopa.utils:
      - sopa.utils.data: api/utils/data.md
  - Toy examples: toy.md
  - Cite us: cite_us.md
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - css/termynal.css
  - css/custom.css
extra_javascript:
  - js/mathjax.js
  - js/termynal.js
  - js/custom.js
