[tool.poetry]
name = "sopa"
version = "0.0.1"
description = "Spatial-omics preprocessing and analysis"
authors = ["Quentin Blampey <quentin.blampey@gmail.com>"]
packages = [{ include = "sopa" }]

[tool.poetry.scripts]
sopa = "sopa.main:app"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
botocore = "^1.31.47"
spatialdata = "^0.0.13"
spatialdata-io = "^0.0.8"
spatial-image = "<1.0.0"
typer = "^0.9.0"
scanpy = "^1.9.5"

[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
isort = "^5.10.1"
pytest = "^7.1.3"
ipykernel = "^6.25.2"
mkdocs-material = "^9.3.2"
memory-profiler = "^0.61.0"


[tool.poetry.group.cellpose.dependencies]
cellpose = "^2.2.3"
opencv-python = "^4.8.0.76"


[tool.poetry.group.baysor.dependencies]
toml = "^0.10.2"
loompy = "^3.0.7"


[tool.poetry.group.tangram.dependencies]
tangram-sc = "^1.0.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"

[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
'''

[tool.isort]
profile = "black"
skip_glob = ["*/__init__.py"]
