read:
  technology: hyperion

patchify:
  patch_width_pixel: 3000
  patch_overlap_pixel: 40

segmentation:
  cellpose:
    diameter: 15
    channels: ["DNA1"]
    flow_threshold: 2
    cellprob_threshold: -6

shapes:
  expand_radius: 2

aggregate:
  average_intensities: true
  min_intensity_ratio: 0.1

explorer:
  ram_threshold_gb: 8
