read:
  technology: blobs

patchify:
  patch_width_pixel: 6000
  patch_overlap_pixel: 150
  patch_width_microns: 1000
  patch_overlap_microns: 20

segmentation:
  cellpose:
    diameter: 60
    channels: ["DAPI"]
    flow_threshold: 2
    cellprob_threshold: -6

shapes:
  expand_radius: 0
  min_area: 2

aggregate:
  average_intensities: true
  gene_column: "genes"

annotation:
  fluorescence:
    marker_cell_dict:
      EPCAM: Tumoral cell
      CD3: T cell
      CD20: B cell

explorer:
  gene_column: "genes"
  ram_threshold_gb: 16

executables:
  baysor: ~/.julia/bin/baysor
