reader:
  name: qptiff
  args:
    channels_renaming:
      DAPI MSI: DAPI
      Opal 780 MSI: CK
      Opal 480 MSI: CD3
      Cy5 MSI: CD31
      FITC: FAP
      Cy3: CD68
      Texas Red: CD20

patchify:
  tile_width_pixel: 4000
  tile_overlap_pixel: 40
  tile_width_microns: 4000
  tile_overlap_microns: 30

segmentation:
  # cellpose:
  #   diameter: 150
  #   channels: ["DAPI"]
  #   flow_threshold: 2
  #   cellprob_threshold: -6
  #   expand_radius: 2

  baysor:
    cell_key: cell_id
    unassigned_value: -1
    config:
      data:
        exclude_genes: "Blank*"      # genes excluded from the Baysor segmentation
        force_2d: true               # if false, uses 3D mode
        min_molecules_per_cell: 30   # min number of transcripts per cell
        x: "x"
        y: "y"
        z: "z"
        gene: "gene"
        min_molecules_per_gene: 0
        min_molecules_per_segment: 8
        confidence_nn_id: 16

      segmentation:
        scale: 6.15                        # typical cell radius
        scale_std: "25%"                   # cell radius standard deviation
        prior_segmentation_confidence: 0.5 # confidence of the cellpose confidence (float in [0, 1])
        estimate_scale_from_centers: false
        n_clusters: 4
        iters: 500
        n_cells_init: 0
        nuclei_genes: ""
        cyto_genes: ""
        new_component_weight: 0.2
        new_component_fraction: 0.3

aggregate:
  intensity_mean: true
  transcript_count: false
  #gene_column: ""

# annotation:
#   fluorescence:
#     marker_cell_dict:
#       CK: Tumoral cell
#       CD3: T cell
#       CD31: Endothelial
#       FAP: Fibroblast
#       CD68: Macrophage
#       CD20: B cell

explorer:
  shapes_key: "polygons"
  gene_column: "gene"

executables:
  baysor: /mnt/beegfs/merfish/bin/baysor/bin/baysor #~/.julia/bin/baysor