reader:
  name: qptiff
  args:
    ...

segmentation:
  name: cellpose
  args:
    diameter: 15
    channels: ["DAPI"]
    tile_width: 3000
    tile_overlap: 50
    expand_radius: 2
  
  # tiling:
  #   name: sequential
  #   args:
  #     tile_width: 3000
  #     tile_overlap: 50
  
  # post-processing:
  #   expand_radius: 0
  #   average_channels_intensities: true

annotation: false

explorer: #TODO: use this
  metadata:
    a: 2