reader:
  name: qptiff
  args:
    channels_renaming:
      DAPI MSI: DAPI
      Opal 780 MSI: CK
      Opal 480 MSI: CD3
      Cy5 MSI: CD31
      FITC: FAP
      Cy3: CD68
      Texas Red: CD20

segmentation:
  name: cellpose
  mode: parallel
  args:
    diameter: 15
    channels: ["DAPI"]
    tile_width: 5000
    tile_overlap: 50
    expand_radius: 2

annotation: false

explorer:
  shapes_key: "polygons"
  gene_column: "gene"