reader:
  name: qptiff
  args:
    channels_renaming:
      DAPI MSI: DAPI
      Opal 780 MSI: CK
      Opal 480 MSI: CD3
      Cy5 MSI: CD31
      FITC: FAP
      Cy3: CD68
      Texas Red: CD20

segmentation:
  name: cellpose
  mode: parralel
  args:
    diameter: 100
    channels: ["DAPI"]
    tile_width: 3000
    tile_overlap: 50
    expand_radius: 2

annotation: false

explorer: #TODO: use this
  shapes_key: "polygons"